"""Versioned mission JSON schema for agent → companion-app handoff.

The agent produces :class:`MissionV1` objects; the
:class:`~skyherd.drone.mavic_adapter.MavicAdapter` serialises them and
forwards to either Leg A (DJI via companion app) or Leg B (MAVSDK via
USB-C OTG).  Both legs parse the same schema.

Versioning policy
-----------------
* ``version`` is a literal int.  Bumping means a breaking change to the
  payload; old companion apps will reject the mission.
* Non-breaking additions (new optional fields) do NOT bump ``version``
  thanks to ``extra="allow"`` on the top-level model.
* Removing or renaming a field IS breaking — bump ``version``.

Current version: 1.

See also :doc:`../docs/MAVIC_MISSION_SCHEMA.md`.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

from skyherd.drone.interface import Waypoint

__all__ = [
    "FailoverHint",
    "MissionMetadata",
    "MissionV1",
    "SCHEMA_VERSION",
]

SCHEMA_VERSION: Literal[1] = 1


class FailoverHint(BaseModel):
    """Optional hint telling the companion app which leg to prefer.

    Attributes
    ----------
    preferred_leg:
        ``"dji"`` forces the DJI primary; ``"mavsdk"`` forces the
        MAVSDK fallback; ``"auto"`` (default) lets the adapter decide.
    retry_on_other_leg:
        When ``True`` (default), the adapter retries a failed actuator
        call on the other leg once before giving up.
    retry_budget:
        Maximum number of leg swaps per mission.  Default ``1``.
        Prevents ping-pong when both legs are unhealthy.
    """

    preferred_leg: Literal["dji", "mavsdk", "auto"] = "auto"
    retry_on_other_leg: bool = True
    retry_budget: int = Field(default=1, ge=0, le=8)


class MissionMetadata(BaseModel):
    """Per-mission safety + attestation metadata.

    ``mission_id`` is a short opaque string (generated by the adapter's
    ``_next_mission_id``) that flows through ledger entries so replay
    tests can trace every event belonging to the same mission.
    """

    mission_id: str = Field(..., min_length=1, max_length=64)
    ranch_id: str = Field(..., min_length=1, max_length=64)
    scenario: str | None = None
    wind_kt: float | None = Field(default=None, ge=0.0, le=100.0)
    battery_floor_pct: float = Field(default=30.0, ge=0.0, le=100.0)
    geofence_version: str | None = None
    issued_ts: float | None = None
    issued_by: str | None = None


class MissionV1(BaseModel):
    """Top-level mission packet sent from agent → companion app.

    ``extra="allow"`` keeps forward compatibility — newer fields added
    in future minor revisions remain parseable by older apps (they'll
    simply ignore unknown fields).

    Attributes
    ----------
    version:
        Schema major version.  Must be ``1``; bumping this is a
        breaking change.
    metadata:
        :class:`MissionMetadata` — ranch/scenario/safety parameters.
    waypoints:
        Ordered list of :class:`~skyherd.drone.interface.Waypoint`.
        Must have at least 1 and at most 64 entries.
    deterrent_tone_hz:
        Optional.  When set, the companion app plays a tone at the
        specified frequency during mission hold.
    deterrent_duration_s:
        Optional.  Duration of the deterrent tone.
    failover:
        :class:`FailoverHint` controlling adapter leg preference.
    """

    model_config = ConfigDict(extra="allow")

    version: Literal[1] = SCHEMA_VERSION
    metadata: MissionMetadata
    waypoints: list[Waypoint] = Field(..., min_length=1, max_length=64)
    deterrent_tone_hz: int | None = Field(default=None, ge=500, le=20000)
    deterrent_duration_s: float | None = Field(default=None, ge=0.0, le=60.0)
    failover: FailoverHint = Field(default_factory=FailoverHint)

    def to_wire(self) -> dict[str, Any]:
        """JSON-compatible dict for MQTT / WebSocket dispatch."""
        return self.model_dump(mode="json")

    @classmethod
    def from_wire(cls, payload: dict[str, Any]) -> MissionV1:
        """Parse a wire-format dict into a :class:`MissionV1` instance.

        Unknown top-level fields are tolerated (forward compat).
        """
        return cls.model_validate(payload)
