#!/usr/bin/env python3
"""
auto_apply_fix.py — Autonomous fix dispatcher for SkyHerd video iteration.

Reads the top-priority fix suggestion from a score markdown report and spawns
a Claude Code subagent to apply the change.  Handles build-failure rollback
and serialises edits on shared files.

Usage:
    python scripts/auto_apply_fix.py \\
        --score-md .planning/research/iter-3-A-score.md \\
        --variant A --iter 3

Options:
    --score-md     Path to aggregate score markdown (from aggregate_score.py)
    --variant      A | B | C
    --iter         Iteration number
    --fix-index    Which fix to apply (1-based, default: 1 = highest priority)
    --dry-run      Print the fix spec without applying
    --skip-compile-check  Skip TypeScript compile verification after fix

Exit codes:
    0  Fix applied and committed successfully
    1  Fix failed (build error) or no fix available — caller should try next
    2  No fixes in score report
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
PROMPTS_DIR = PROJECT_ROOT / "scripts" / "prompts"
FIX_PROMPT = PROMPTS_DIR / "auto-apply-fix.md"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("auto_apply_fix")

# Max lines changed before we flag it as potentially dangerous
SAFE_DIFF_LINES = 120

# ── Parse fix suggestions from score md ───────────────────────────────────────

_FIX_BLOCK_RE = re.compile(
    r"### Fix (\d+).*?\n"
    r".*?\*\*Frame:\*\*\s*`([^`]*)`.*?\n"
    r".*?\*\*File:\*\*\s*`([^`]*)`.*?\n"
    r".*?\*\*Change:\*\*\s*(.+?)(?=\n\n|\Z)",
    re.DOTALL,
)


def parse_fixes_from_score_md(md_path: Path) -> list[dict]:
    """
    Extract fix suggestions from a score markdown generated by aggregate_score.py.
    Returns list of dicts with keys: priority, frame, file_path, change.
    """
    if not md_path.exists():
        raise FileNotFoundError(f"Score md not found: {md_path}")

    content = md_path.read_text()
    fixes: list[dict] = []

    for m in _FIX_BLOCK_RE.finditer(content):
        priority = int(m.group(1))
        frame = m.group(2).strip()
        file_path = m.group(3).strip()
        change = m.group(4).strip()
        fixes.append(
            {
                "priority": priority,
                "frame": frame,
                "file_path": file_path,
                "change": change,
            }
        )

    fixes.sort(key=lambda x: x["priority"])
    return fixes


# ── Build the prompt for the Claude Code subagent ─────────────────────────────


def build_fix_prompt(
    fix: dict,
    variant: str,
    iter_num: int,
    context: str = "",
) -> str:
    """
    Build the --print prompt that gets passed to `claude --dangerously-skip-permissions -p`.
    """
    system_prompt = FIX_PROMPT.read_text() if FIX_PROMPT.exists() else ""

    prompt = (
        f"{system_prompt}\n\n"
        f"---\n\n"
        f"## Fix specification\n\n"
        f"TARGET_FILE: {fix['file_path']}\n"
        f"CHANGE_SPEC: {fix['change']}\n"
        f"VARIANT: {variant}\n"
        f"ITER: {iter_num}\n"
        f"CONTEXT: Frame {fix['frame']} — {context}\n\n"
        f"Apply the fix now."
    )
    return prompt


# ── Git helpers ────────────────────────────────────────────────────────────────


def git_rev_parse_head() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def git_revert_to(sha: str) -> None:
    log.warning("Reverting to %s due to build failure", sha)
    subprocess.run(
        ["git", "checkout", sha, "--", "."],
        cwd=PROJECT_ROOT,
        check=True,
    )


def run_ts_compile() -> bool:
    """Run TypeScript compile check. Returns True if clean."""
    result = subprocess.run(
        ["npx", "tsc", "--noEmit"],
        cwd=PROJECT_ROOT / "remotion-video",
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        log.error("TypeScript compile FAILED:\n%s", result.stdout + result.stderr)
        return False
    return True


def count_diff_lines() -> int:
    """Count lines changed since last commit."""
    result = subprocess.run(
        ["git", "diff", "--stat", "HEAD"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
    )
    match = re.search(r"(\d+) insertions?.*?(\d+) deletions?", result.stdout)
    if match:
        return int(match.group(1)) + int(match.group(2))
    return 0


# ── Spawn Claude Code subagent ────────────────────────────────────────────────


def apply_fix_via_subagent(
    fix: dict,
    variant: str,
    iter_num: int,
    skip_compile: bool = False,
) -> dict:
    """
    Spawn `claude --dangerously-skip-permissions -p <prompt>` to apply the fix.
    Returns {"status": "success|failed", "summary": str, "diff_lines": int}.
    """
    head_before = git_rev_parse_head()

    prompt = build_fix_prompt(fix, variant, iter_num)

    log.info(
        "Spawning Claude Code subagent for fix: %s → %s",
        fix["file_path"],
        fix["change"][:80],
    )

    # Write prompt to a temp file to avoid shell quoting issues
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, prefix="fix-prompt-"
    ) as tmp:
        tmp.write(prompt)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            [
                "claude",
                "--dangerously-skip-permissions",
                "--print",
                "-p",
                prompt,
            ],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=300,  # 5 min hard limit per fix
        )
    except subprocess.TimeoutExpired:
        log.error("Claude Code subagent timed out after 300s")
        return {"status": "failed", "summary": "Subagent timeout", "diff_lines": 0}
    except FileNotFoundError:
        log.error("'claude' binary not found — is Claude Code CLI installed?")
        return {
            "status": "failed",
            "summary": "claude CLI not found",
            "diff_lines": 0,
        }
    finally:
        os.unlink(tmp_path)

    output = result.stdout + result.stderr
    log.debug("Subagent output:\n%s", output[:2000])

    # Parse JSON result from subagent output (last JSON object in stdout)
    agent_result: dict = {}
    for line in reversed(result.stdout.splitlines()):
        line = line.strip()
        if line.startswith("{") and line.endswith("}"):
            try:
                agent_result = json.loads(line)
                break
            except json.JSONDecodeError:
                continue

    if agent_result.get("status") == "success":
        diff_lines = count_diff_lines()
        log.info("Fix applied successfully. diff_lines=%d", diff_lines)

        # Safety guard: warn if diff is very large
        if diff_lines > SAFE_DIFF_LINES:
            log.warning(
                "Diff is large (%d lines) — expected surgical change <50 lines",
                diff_lines,
            )

        # Verify compile (unless skipped)
        if not skip_compile:
            if not run_ts_compile():
                log.error("TypeScript compile failed after fix — reverting")
                git_revert_to(head_before)
                return {
                    "status": "failed",
                    "summary": f"TypeScript compile failed after fix; reverted to {head_before[:8]}",
                    "diff_lines": 0,
                }

        return {
            "status": "success",
            "summary": agent_result.get("summary", "Fix applied"),
            "diff_lines": diff_lines,
        }

    # Subagent reported failure or returned no result
    head_after = git_rev_parse_head()
    if head_after != head_before:
        # Something was committed — check compile anyway
        if not skip_compile and not run_ts_compile():
            git_revert_to(head_before)
            return {
                "status": "failed",
                "summary": "Partial commit detected; TypeScript failed; reverted",
                "diff_lines": 0,
            }

    return {
        "status": "failed",
        "summary": agent_result.get("summary", "Subagent reported failure"),
        "diff_lines": 0,
    }


# ── Main ───────────────────────────────────────────────────────────────────────


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--score-md", required=True, help="Path to score markdown report")
    p.add_argument("--variant", required=True, choices=["A", "B", "C"])
    p.add_argument("--iter", type=int, required=True)
    p.add_argument("--fix-index", type=int, default=1, help="1-based fix priority to apply")
    p.add_argument("--dry-run", action="store_true", help="Print fix spec without applying")
    p.add_argument("--skip-compile-check", action="store_true")
    return p


def main() -> int:
    args = build_parser().parse_args()

    md_path = Path(args.score_md)

    try:
        fixes = parse_fixes_from_score_md(md_path)
    except FileNotFoundError as exc:
        log.error("%s", exc)
        return 1

    if not fixes:
        log.info("No fix suggestions found in %s", md_path)
        print("NO_FIXES")
        return 2

    # Select fix by index (1-based)
    fix_idx = args.fix_index - 1
    if fix_idx >= len(fixes):
        log.error(
            "Fix index %d out of range (only %d fixes available)",
            args.fix_index,
            len(fixes),
        )
        return 1

    fix = fixes[fix_idx]
    log.info(
        "Selected fix %d/%d: %s → %s",
        args.fix_index,
        len(fixes),
        fix["file_path"],
        fix["change"][:80],
    )

    if args.dry_run:
        print(json.dumps(fix, indent=2))
        return 0

    result = apply_fix_via_subagent(
        fix=fix,
        variant=args.variant,
        iter_num=args.iter,
        skip_compile=args.skip_compile_check,
    )

    print(json.dumps(result))

    if result["status"] == "success":
        log.info(
            "✓ Fix applied: %s (%d diff lines)",
            result["summary"][:100],
            result["diff_lines"],
        )
        return 0

    log.error("✗ Fix failed: %s", result["summary"])
    return 1


if __name__ == "__main__":
    sys.exit(main())
