#!/usr/bin/env bash
# provision-edge.sh — Bootstrap a Raspberry Pi 4 as a SkyHerd edge node.
#
# Usage (run from your laptop via SSH pipe):
#   ssh pi@edge-house 'bash -s' < scripts/provision-edge.sh edge-house "trough_1,trough_2"
#   ssh pi@edge-barn  'bash -s' < scripts/provision-edge.sh edge-barn  "trough_3,trough_4,trough_5,trough_6"
#
# The script is idempotent — safe to re-run.

set -euo pipefail

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------

EDGE_ID="${1:?Usage: provision-edge.sh <edge-id> <trough-ids>}"
EDGE_TROUGH_IDS="${2:?Usage: provision-edge.sh <edge-id> <trough-ids>}"

# Defaults — override by passing extra env before the script:
#   RANCH_ID=ranch_b MQTT_URL=mqtt://10.0.0.5:1883 ssh pi@host 'bash -s' < ...
RANCH_ID="${RANCH_ID:-ranch_a}"
MQTT_URL="${MQTT_URL:-mqtt://192.168.1.100:1883}"
SKYHERD_REPO="${SKYHERD_REPO:-https://github.com/george11642/skyherd-engine}"
INSTALL_DIR="${INSTALL_DIR:-/opt/skyherd-engine}"
SERVICE_USER="${SERVICE_USER:-skyherd}"
EDGE_DETECTOR_MODE="${EDGE_DETECTOR_MODE:-rule}"
EDGE_CAPTURE_INTERVAL_S="${EDGE_CAPTURE_INTERVAL_S:-10}"
EDGE_HEARTBEAT_INTERVAL_S="${EDGE_HEARTBEAT_INTERVAL_S:-30}"
EDGE_HEALTHZ_PORT="${EDGE_HEALTHZ_PORT:-8787}"
LOG_LEVEL="${LOG_LEVEL:-INFO}"

echo "============================================================"
echo " SkyHerd Edge Provisioner"
echo " EDGE_ID          = ${EDGE_ID}"
echo " EDGE_TROUGH_IDS  = ${EDGE_TROUGH_IDS}"
echo " RANCH_ID         = ${RANCH_ID}"
echo " MQTT_URL         = ${MQTT_URL}"
echo " INSTALL_DIR      = ${INSTALL_DIR}"
echo " DETECTOR_MODE    = ${EDGE_DETECTOR_MODE}"
echo "============================================================"

# ---------------------------------------------------------------------------
# Step 1 — System packages
# ---------------------------------------------------------------------------

echo ""
echo "[1/8] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y \
    git \
    curl \
    python3-picamera2 \
    mosquitto-clients \
    libcamera-apps \
    --no-install-recommends

# ---------------------------------------------------------------------------
# Step 2 — Install uv (Astral package manager)
# ---------------------------------------------------------------------------

echo ""
echo "[2/8] Installing uv..."
if ! command -v uv &>/dev/null; then
    curl -sSf https://astral.sh/uv/install.sh | sh
    # Make uv available in this shell session
    export PATH="$HOME/.cargo/bin:$PATH"
    export PATH="$HOME/.local/bin:$PATH"
fi
echo "uv version: $(uv --version)"

# ---------------------------------------------------------------------------
# Step 3 — Clone / update skyherd-engine
# ---------------------------------------------------------------------------

echo ""
echo "[3/8] Cloning/updating skyherd-engine..."
if [ -d "${INSTALL_DIR}/.git" ]; then
    echo "  Repo exists — pulling latest..."
    sudo -u "${SERVICE_USER}" git -C "${INSTALL_DIR}" pull --rebase origin main 2>/dev/null \
        || git -C "${INSTALL_DIR}" pull --rebase origin main
else
    sudo mkdir -p "${INSTALL_DIR}"
    sudo chown "${USER}:${USER}" "${INSTALL_DIR}"
    git clone "${SKYHERD_REPO}" "${INSTALL_DIR}"
fi

# ---------------------------------------------------------------------------
# Step 4 — Create system user (idempotent)
# ---------------------------------------------------------------------------

echo ""
echo "[4/8] Ensuring service user '${SERVICE_USER}'..."
if ! id "${SERVICE_USER}" &>/dev/null; then
    sudo useradd --system --shell /bin/false \
        --home-dir "${INSTALL_DIR}" "${SERVICE_USER}"
fi
sudo chown -R "${SERVICE_USER}:${SERVICE_USER}" "${INSTALL_DIR}"

# Add service user to video group for camera access
sudo usermod -aG video "${SERVICE_USER}" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Step 5 — Install Python dependencies
# ---------------------------------------------------------------------------

echo ""
echo "[5/8] Installing Python dependencies (uv sync --extra edge)..."
sudo -u "${SERVICE_USER}" \
    env PATH="${INSTALL_DIR}/.venv/bin:$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:/usr/bin" \
    uv --project "${INSTALL_DIR}" sync --extra edge

# ---------------------------------------------------------------------------
# Step 6 — Write /etc/skyherd/edge.env
# ---------------------------------------------------------------------------

echo ""
echo "[6/8] Writing /etc/skyherd/edge.env..."
sudo mkdir -p /etc/skyherd
sudo tee /etc/skyherd/edge.env > /dev/null <<EOF
# Generated by provision-edge.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edge ID: ${EDGE_ID}

# ---- Required ----
RANCH_ID=${RANCH_ID}
MQTT_URL=${MQTT_URL}

# ---- Node identity ----
EDGE_ID=${EDGE_ID}
EDGE_TROUGH_IDS=${EDGE_TROUGH_IDS}

# ---- Detector ----
EDGE_DETECTOR_MODE=${EDGE_DETECTOR_MODE}

# ---- Capture ----
EDGE_CAPTURE_INTERVAL_S=${EDGE_CAPTURE_INTERVAL_S}

# ---- Observability ----
EDGE_HEARTBEAT_INTERVAL_S=${EDGE_HEARTBEAT_INTERVAL_S}
EDGE_HEALTHZ_PORT=${EDGE_HEALTHZ_PORT}
LOG_LEVEL=${LOG_LEVEL}
EOF

sudo chmod 640 /etc/skyherd/edge.env
sudo chown root:${SERVICE_USER} /etc/skyherd/edge.env
echo "  Wrote /etc/skyherd/edge.env"

# ---------------------------------------------------------------------------
# Step 7 — Install systemd service
# ---------------------------------------------------------------------------

echo ""
echo "[7/8] Installing systemd service..."
sudo cp "${INSTALL_DIR}/src/skyherd/edge/systemd/skyherd-edge.service" \
        /etc/systemd/system/skyherd-edge.service

# Patch WorkingDirectory to match install location
sudo sed -i "s|WorkingDirectory=.*|WorkingDirectory=${INSTALL_DIR}|" \
    /etc/systemd/system/skyherd-edge.service
sudo sed -i "s|ExecStart=.*|ExecStart=${INSTALL_DIR}/.venv/bin/skyherd-edge run|" \
    /etc/systemd/system/skyherd-edge.service
sudo sed -i "s|Environment=\"PATH=.*\"|Environment=\"PATH=${INSTALL_DIR}/.venv/bin:/usr/local/bin:/usr/bin\"|" \
    /etc/systemd/system/skyherd-edge.service

sudo systemctl daemon-reload
sudo systemctl enable --now skyherd-edge

echo "  Service enabled and started."

# ---------------------------------------------------------------------------
# Step 8 — Verify + tail logs
# ---------------------------------------------------------------------------

echo ""
echo "[8/8] Verifying service status..."
sleep 2
sudo systemctl status skyherd-edge --no-pager || true

echo ""
echo "============================================================"
echo " Provisioning complete for ${EDGE_ID}!"
echo " Tailing journalctl for 15 s — you should see heartbeats."
echo " Ctrl-C to exit early."
echo "============================================================"
echo ""
timeout 15 sudo journalctl -u skyherd-edge -f --no-pager 2>/dev/null || true

echo ""
echo "Done. Verify on broker:"
echo "  mosquitto_sub -v -t 'skyherd/${RANCH_ID}/edge_status/${EDGE_ID}'"
